// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Trnk_g5UzDehFl3M9FXawS8itlAq3Mo',
    appId: '1:871732195937:web:c099b30765e72fe4a27020',
    messagingSenderId: '871732195937',
    projectId: 'learn-with-maple',
    authDomain: 'learn-with-maple.firebaseapp.com',
    storageBucket: 'learn-with-maple.appspot.com',
    measurementId: 'G-GG7BQPJS1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9tNeCgRepfQclUij7JuFkCwy1j7SgXDU',
    appId: '1:871732195937:android:056f85b975fe0c90a27020',
    messagingSenderId: '871732195937',
    projectId: 'learn-with-maple',
    storageBucket: 'learn-with-maple.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY6VaR8NY1mliLC_VLIQ96AqViFdo5be4',
    appId: '1:871732195937:ios:43d59daad6abe045a27020',
    messagingSenderId: '871732195937',
    projectId: 'learn-with-maple',
    storageBucket: 'learn-with-maple.appspot.com',
    androidClientId: '871732195937-s3ldvc61jh487ovvkmu1h1jhp5kfasnp.apps.googleusercontent.com',
    iosClientId: '871732195937-b5fhl6jhkt3agoo7v6mjbdi08ou2s13g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY6VaR8NY1mliLC_VLIQ96AqViFdo5be4',
    appId: '1:871732195937:ios:770722afe0baca66a27020',
    messagingSenderId: '871732195937',
    projectId: 'learn-with-maple',
    storageBucket: 'learn-with-maple.appspot.com',
    androidClientId: '871732195937-s3ldvc61jh487ovvkmu1h1jhp5kfasnp.apps.googleusercontent.com',
    iosClientId: '871732195937-6fn0chvq5lgvd6p80ri1td1oicobkhbb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
